### ISSUE TITLE
Playable yet?

### ISSUE THREAD

**Issue by Peyton2017** [DenizBasgoren/agario#1]
Is your project run-able/playable? If so, could you provide some instructions?

**Comment by Peyton2017** [comment]
Figured it out. When do you think you'll be finished with the project?

**Comment by DenizBasgoren** [comment]
Hello, game is currently playable and already is deployed on heroku:
https://node-agario-clone.herokuapp.com/
It currently has collision-detection functionality missing, and it also has a small issue with fps, all of which I will fix on this or upcoming week. I will also add an installation guide and source code documentation. 
For now, to run the project locally, use the following commands

Install the dependencies:
`npm install`

Run the parcel bundler, which transpiles react code, minifies and starts a hotdev server
`npm run watch`

Run the node server
`npm run start`

Then go to `localhost:3000`

**Comment by DenizBasgoren** [comment]
V1 published! Enjoy
